### PR TITLE
feat: Deploy minor, major and developements channels to docker.

### PR DESCRIPTION
**Pull request by fabulator**
- Add support for developement channel. Eg. on beta channel, it will not push docker image to latest but to beta
- Update all versions in docker. Eg. when you upload version 7.3.10, it will also update 7.3 and 7 (and latest)

### CODE REVIEW

**Comment by sc250024** [comment]
Would be really nice if we could get this merged!

**Comment by twelvelabs** [comment]
This seems really useful, but does introduce a new tags that weren't previously being pushed by this plugin. Maybe the prerelease and major/minor tags could be make opt-in?

I would guess that doing so would also make this more likely to be merged.

**Comment by christiansiegel** [comment]
> This seems really useful, but does introduce a new tags that weren't previously being pushed by this plugin. Maybe the prerelease and major/minor tags could be make opt-in?

How about?:
- `publishMajor` (default: `false`)
- `publishMajorMinor` (default: `false`)
- `publishPrerelease` (default: `false`)

**Comment by christiansiegel** [comment]
Alternative solution with tag templates: PR #35

**Pull request closed without merging**
